### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by pdehlke** [movableink/doorman#32]
pete@dashboard1:~$ node -v
v0.10.26
pete@dashboard1:~$ git clone https://github.com/movableink/doorman
Cloning into 'doorman'...
remote: Counting objects: 484, done.
remote: Total 484 (delta 0), reused 0 (delta 0), pack-reused 484
Receiving objects: 100% (484/484), 148.20 KiB | 0 bytes/s, done.
Resolving deltas: 100% (223/223), done.
Checking connectivity... done.
pete@dashboard1:~$ cd doorman/
pete@dashboard1:~/doorman$ npm install
<100s of lines>
pete@dashboard1:~/doorman$ wget https://gist.githubusercontent.com/pdehlke/68f6303e73da26c168a1/raw/8b04cd00ba191c1b3b1e59a7e2523eecb38cac79/gistfile1.js -O conf.js -q
pete@dashboard1:~/doorman$ node app.js

util.js:555
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:555:43)
    at Object.<anonymous> (/home/pete/doorman/node_modules/http-proxy/lib/http-proxy/index.js:108:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pete/doorman/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
pete@dashboard1:~/doorman$

Same result with node 0.12.0

There are no files named util.js on this machine that have more than 319 lines, and no files named util.js contain the string 'superCtor'.

Admittedly, I know nearly nothing of node. Any help with this?

**Comment by inakianduaga** [comment]
+1, same crash, node version `v0.10.38`, running inside the dockerized `google/nodejs` base image

**Comment by AlexRRR** [comment]
This is a bug for me too. npm starts throws
```javascript
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
```
